#!/bin/bash
readonly CONTAINER_NAME=${1:-$(basename $(pwd) | sed -e 's;.git;;g')}

if [ ! "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
  podman kill "${CONTAINER_NAME}"
else
  echo "No container ${CONTAINER_NAME} running."
 # podman rm -f "${CONTAINER_NAME}"
fi
