#!/bin/bash
readonly CONTAINER_IMAGE=${CONTAINER_IMAGE:-'localhost/ubi8-ansible'}
readonly CONTAINER_NAME=${1:-$(basename $(pwd) | sed -e 's;.git;;g')}

readonly INVENTORY_FILE=${2:-'inventory/localhost'}
readonly ROOT_CMD=${ROOT_CMD:-"/usr/sbin/init"}

add_inventory_to_hosts() {
  if [ -e "${INVENTORY_FILE}" ]; then
    local hosts_list_file=$(mktemp)
    trap "rm -f ${hosts_list_file}" EXIT

    cat "${INVENTORY_FILE}" | grep -e '^\[' | sed -e 's;\[;;' -e 's;\];;' | sed -e '/:/d' -e '/^$/d' > "${hosts_list_file}"
    dos2unix "${hosts_list_file}" 2> /dev/null
    cat "${hosts_list_file}" | \
    while
      read line
    do
      for i in {0..3}
      do
        echo -n "--add-host ${line}-${i}:127.0.0.1 "
      done
    done
  fi
}

add_extra_volumes() {
  if [ -n "${PODRUN_EXTRA_VOLUMES}" ]; then
    echo "${PODRUN_EXTRA_VOLUMES}"
  fi
}

add_port_bindings() {
  if [ -n "${PORTS_BINDING}" ]; then
    echo -p 8080:8080 -p 9990:9990
  fi
}

if [ ! "$(podman ps -q -f name=${CONTAINER_NAME})" ]; then
  podman run -dit --systemd=true --privileged=true  \
       --rm --name "${CONTAINER_NAME}" --workdir /work -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $(pwd):/work:rw \
       $(add_inventory_to_hosts) $(add_port_bindings) \
       "${CONTAINER_IMAGE}" \
       "${ROOT_CMD}"
fi
podman exec -ti "${CONTAINER_NAME}" /bin/bash
